### ISSUE TITLE
Chrome browser tells me going to compmodels.com is unsafe

### ISSUE THREAD

**Issue by martinholmer** [comp-org/comp-ce#125] opened 2019-04-25 13:30 UTC
I'm assuming one of the main entry paths to the TaxBrain web app is from the lower-right-hand icon on the following page at the OSPC "Portfolio" page:

<img width="1044" alt="Screen Shot 2019-04-25 at 9 13 23 AM" src="https://user-images.githubusercontent.com/12170745/56739168-16385500-673c-11e9-8445-d59b520d5e29.png">

When people using the Chrome browser click on that icon, they get the following page:

<img width="675" alt="Screen Shot 2019-04-25 at 9 11 36 AM" src="https://user-images.githubusercontent.com/12170745/56739339-6b746680-673c-11e9-8236-8bba0892cd99.png">

@hdoupe, I don't think this is the impression you want to be giving people.

@MattHJensen @andersonfrailey

**Comment by hdoupe** [comment] 2019-04-25 14:11
Thanks for the bug report @martinholmer. There's an issue with compmodels.com forwarding to compmodels.org. You can go directly to [compmodels.org](https://www.compmodels.org) and I can assure that it is safe.

@peter-metz can you update the link on ospc.org website?

**Comment by hdoupe** [comment] 2019-04-25 14:21
The issue is that most people have http**s**://www.compmodels.com in their browser cache, but Go Daddy forwarding only works when users enter http://www.compmodels.com URLs (not http**s**). So, http://www.compmodels.com forwards just fine. The only way that I can think to resolve the HTTPS forwarding issue is to setup a landing page at compmodels.com that asks users to go to compmodels.org.

**Comment by martinholmer** [comment] 2019-04-25 14:32
@hdoupe,  Are you saying that the COMP system that includes the TaxBrain webapp is hosted on **Go Daddy**?

**Comment by hdoupe** [comment] 2019-04-25 14:35
No, but it's domain is registered with Go Daddy, a very popular domain registry.

**Comment by Peter-Metz** [comment] 2019-04-25 14:37
The link on the website is now fixed. Thanks for pointing this out @martinholmer 

cc: @hdoupe

**Comment by hdoupe** [comment] 2019-04-25 14:37
Thanks @Peter-Metz!

**Comment by hdoupe** [comment] 2019-04-26 14:54
Resolved. Thanks for the bug report @martinholmer.

**Closed by hdoupe** 2019-04-26 14:54 UTC
